using System.Linq;
using Content.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.SS220.ApproveMaths;

namespace Content.Client.SS220.ApproveMaths
{
    [GenerateTypedNameReferences]
    public sealed partial class ApproveMathsWindow : DefaultWindow
    {
        public event Action<UiButton>? OnApproveButton;
        public ApproveMathsWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            CheckButton.OnPressed += _ => OnApproveButton?.Invoke(UiButton.Check);
        }

    }
}
