using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Questionnaire;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Questionnaire;

[GenerateTypedNameReferences]
public sealed partial class QuestionnaireWindow : FancyWindow
{
    private Dictionary<int, Label> _questions = new ();
    private Dictionary<int, List<string>> _answers = new();

    public event Action<QuestionnaireResponse>? OnSubmitAction;

    public QuestionnaireWindow(QuestionnairePrototype prototype)
    {
        RobustXamlLoader.Load(this);

        BuildQuestions(prototype);

        SubmitButton.OnPressed += _ => TrySubmit();
    }

    private void BuildQuestions(QuestionnairePrototype prototype)
    {
        var questionIndex = 0;

        foreach (var question in prototype.Questions)
        {
            var index = questionIndex;

            var questionBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 5
            };

            var label = new Label
            {
                Text = question.Text,
                FontColorOverride = Color.LightGray
            };

            var control = question.Type switch
            {
                QuestionType.Single => BuildSingleChoiceControl(question, index),
                QuestionType.Multiple => BuildMultiChoiceControl(question, index),
                QuestionType.FreeText => BuildTextControl(index),
                _ => throw new ArgumentOutOfRangeException()
            };

            _questions[index] = label;

            questionBox.AddChild(label);
            questionBox.AddChild(control);
            QuestionsContainer.AddChild(questionBox);

            questionIndex++;
        }
    }

    private Control BuildTextControl(int index)
    {
        var lineEdit = new LineEdit
        {
            PlaceHolder = "Введите ответ...",
        };

        lineEdit.OnTextChanged += args => _answers[index] = [args.Text];

        return lineEdit;
    }

    private Control BuildSingleChoiceControl(QuestionData question, int index)
    {
        var optionButton = new OptionButton();

        if (question.Options.Count <= 0)
            return optionButton;

        foreach (var option in question.Options)
        {
            optionButton.AddItem(option);
        }

        optionButton.OnItemSelected += args =>
        {
            optionButton.SelectId(args.Id);
            _answers[index] = [question.Options[args.Id]];
        };

        return optionButton;
    }

    private Control BuildMultiChoiceControl(QuestionData question, int index)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
        };

        var selectedOptions = new HashSet<string>();

        foreach (var option in question.Options)
        {
            var checkBox = new CheckBox
            {
                Text = option,
            };

            var currentOption = option;

            checkBox.OnToggled += args =>
            {
                if (args.Pressed)
                    selectedOptions.Add(currentOption);
                else
                    selectedOptions.Remove(currentOption);

                _answers[index] = new List<string>(selectedOptions);
            };

            box.AddChild(checkBox);
        }

        return box;
    }

    private void TrySubmit()
    {
        var isValid = true;
        ErrorLabel.Visible = false;

        foreach (var quest in _questions.Values)
        {
            quest.FontColorOverride = Color.LightGray;
        }

        foreach (var (index, quest) in _questions)
        {
            var isCorrect = !(_answers.TryGetValue(index, out var answerList)
                              && answerList.Count > 0
                              && string.IsNullOrWhiteSpace(answerList[0]));

            if (isCorrect)
                continue;

            quest.FontColorOverride = Color.Red;
            isValid = false;
        }

        if (!isValid)
        {
            ErrorLabel.Visible = true;
            return;
        }

        OnSubmitAction?.Invoke(new QuestionnaireResponse
        {
            Answers = _answers
        });

        Close();
    }
}

