using System.Text.RegularExpressions;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Rename;

[GenerateTypedNameReferences]
public sealed partial class RenameWindow : DefaultWindow
{
    private readonly RenameBoundUserInterface _owner;
    private static readonly Regex Expressions = new("[^А-Яа-яёЁ0-9' \\-?!,.]");

    private readonly int _minСharacters = 4;
    public RenameWindow(RenameBoundUserInterface owner)
    {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _owner = owner;

            ConfirmButton.OnPressed += _ => SubmitName();
            NameInput.OnTextEntered += _ => SubmitName();
    }

    private void SubmitName()
    {
        if (NameInput.Text.Length < _minСharacters ||
            NameInput.Text.Length > HumanoidCharacterProfile.MaxNameLength ||
            Expressions.IsMatch(NameInput.Text))
        {
            IncorrectData.Visible = true;
            return;
        }

        _owner.SubmitName(NameInput.Text);
    }

}

