using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Rename;

[GenerateTypedNameReferences]
public sealed partial class RenameWindow : Control
{
    public RenameWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

