name: "Labels: Approve"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v4 
      - name: check all revs
        id: check_approvals
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const requiredApprovals = context.payload.pull_request.requested_reviewers.length;
            const approvedReviews = reviews.filter(review => review.state === 'APPROVED').length;

            return approvedReviews >= requiredApprovals;

      - name: rm labels
        if: steps.check_approvals.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToRemove = ['Status: Needs Review', 'Status: Awaiting Changes'];
            const currentLabels = context.payload.pull_request.labels.map(label => label.name);

            for (const label of labelsToRemove) {
              if (currentLabels.includes(label)) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  name: label,
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: rm label 2
        if: steps.check_approvals.outputs.result == 'true'
        run: |
            curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/SerbiaStrong-220/space-station-14/issues/${{github.event.pull_request.number}}/labels/'Status: Needs Review'
